service: serverless-api-example

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  region: "eu-west-1"
  name: aws
  runtime: go1.x

custom:
  - serverless-jetpack

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  users:
    handler: bin/users
    environment:
      TABLE_NAME: "example-users"
      AWS_REGION: "eu-west-1"
    events:
      - http:
          path: /{any+}
          method: ANY
          cors: true
