service: serverless-api-example

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

custom:
  - serverless-jetpack

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  users:
    handler: bin/users
    events:
      - http:
          path: /{any+}
          method: ANY
          cors: true
